"""added Transfer model

Revision ID: 63d2bea28e5f
Revises: 6467e2ec577a
Create Date: 2023-05-21 14:40:28.269954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63d2bea28e5f'
down_revision = '6467e2ec577a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
